// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gussf/go-mqtt-server/cmd/api"
	"github.com/gussf/go-mqtt-server/domain/usecases/publisher"
	"github.com/gussf/go-mqtt-server/gateways/mqtt"
	"net"
)

// Injectors from wire.go:

func InitializeServer(addr net.Addr) *Server {
	usecase := publisher.NewUsecase()
	requestParser := mqtt.NewMQTTParser(usecase)
	apiAPI := api.NewAPI(requestParser)
	server := NewServer(apiAPI, addr)
	return server
}
